//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.36014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMyCard.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetMyCard.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse :.
        /// </summary>
        public static string AdresseTexte {
            get {
                return ResourceManager.GetString("AdresseTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get My Card.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos Contact.
        /// </summary>
        public static string ContactInfoText {
            get {
                return ResourceManager.GetString("ContactInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CodePostal :.
        /// </summary>
        public static string CPTexte {
            get {
                return ResourceManager.GetString("CPTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importer.
        /// </summary>
        public static string ImporterPhotoTexte {
            get {
                return ResourceManager.GetString("ImporterPhotoTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logo de l&apos;entreprise :.
        /// </summary>
        public static string LogoTexte {
            get {
                return ResourceManager.GetString("LogoTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ma carte.
        /// </summary>
        public static string MaCarteText {
            get {
                return ResourceManager.GetString("MaCarteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail :.
        /// </summary>
        public static string MailTexte {
            get {
                return ResourceManager.GetString("MailTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationalité :.
        /// </summary>
        public static string NationaliteTexte {
            get {
                return ResourceManager.GetString("NationaliteTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom :.
        /// </summary>
        public static string NomTexte {
            get {
                return ResourceManager.GetString("NomTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun appareil trouvé !.
        /// </summary>
        public static string NoPeersTexte {
            get {
                return ResourceManager.GetString("NoPeersTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activer l&apos;agent :.
        /// </summary>
        public static string ParamAgentTexte {
            get {
                return ResourceManager.GetString("ParamAgentTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string ParamètresText {
            get {
                return ResourceManager.GetString("ParamètresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partage.
        /// </summary>
        public static string PartageTexte {
            get {
                return ResourceManager.GetString("PartageTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays :.
        /// </summary>
        public static string PaysTexte {
            get {
                return ResourceManager.GetString("PaysTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appareil(s) trouvé(s) :.
        /// </summary>
        public static string PeersFoundTexte {
            get {
                return ResourceManager.GetString("PeersFoundTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo :.
        /// </summary>
        public static string PhotoTexte {
            get {
                return ResourceManager.GetString("PhotoTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous recevoir la carte de visite de {0} ?.
        /// </summary>
        public static string PopupPartageTexte {
            get {
                return ResourceManager.GetString("PopupPartageTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de partage.
        /// </summary>
        public static string PopupPartageTitre {
            get {
                return ResourceManager.GetString("PopupPartageTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon porte-cartes.
        /// </summary>
        public static string PorteCartesPage {
            get {
                return ResourceManager.GetString("PorteCartesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poste :.
        /// </summary>
        public static string PosteTexte {
            get {
                return ResourceManager.GetString("PosteTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom :.
        /// </summary>
        public static string PrenomTexte {
            get {
                return ResourceManager.GetString("PrenomTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fr-FR.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher des périphériques.
        /// </summary>
        public static string SearchPeriphTexte {
            get {
                return ResourceManager.GetString("SearchPeriphTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partager ma carte de visite.
        /// </summary>
        public static string ShareCDVTexte {
            get {
                return ResourceManager.GetString("ShareCDVTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site web :.
        /// </summary>
        public static string SiteWebTexte {
            get {
                return ResourceManager.GetString("SiteWebTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Société :.
        /// </summary>
        public static string SocieteTexte {
            get {
                return ResourceManager.GetString("SocieteTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone fixe :.
        /// </summary>
        public static string TelFixeTexte {
            get {
                return ResourceManager.GetString("TelFixeTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone portable :.
        /// </summary>
        public static string TelPortTexte {
            get {
                return ResourceManager.GetString("TelPortTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville :.
        /// </summary>
        public static string VilleTexte {
            get {
                return ResourceManager.GetString("VilleTexte", resourceCulture);
            }
        }
    }
}
